// src/services/PathMappingService.js
class PathMappingService {
    constructor() {
      // 하드코딩된 매핑 데이터
      this.mappings = {
            "로카페이>결제>타사결제요청>PC/모바일로카페이호출화면": "로카페이>결제>타사결제요청>PC/모바일로카페이호출화면",
            "front>satellite>main>card": "카드>메인",
            "front>my>payments>weekly": "정기결제>생활요금>위클리",
            "front>my>payments>regular>life-charge>electricity": "정기결제>생활요금>전기요금",
            "MAIN>스플래쉬>접근권한안내": "MAIN>스플래쉬>접근권한안내",
            "설정": "설정",
            "로카페이>공통>인증>간편번호입력": "로카페이>공통>인증>인증수단",
            "front>benefit>app-tech>locatto": "혜택>앱태크>로카토",
            "로카페이>결제>타사결제요청>결제완료": "로카페이>결제>타사결제요청>결제완료",
            "front>my>payments>regular>collection>services": "정기결제>전체",
            "혜택>혜택리포트": "(not set)",
            "main": "띵샵>메인",
            "front>satellite>finance": "금융",
            "front>my>payments>regular>collection": "MY>정기결제>전체",
            "app>spa-menu.lc": "전체메뉴",
            "MAIN>스플래쉬": "MAIN>스플래쉬",
            "spa>my>usage-payment": "MY>결제예정금액>결제예정금액",
            "spa>intergrated-search": "통합검색",
            "app>LPMCDCB_V200.lc": "MEMBERS>MobileWeb로그인>로그인",
            "spa>my>usage-history": "MY>이용내역(매출전표)>이용내역(매출전표)",
            "로그인>지문로그인>지문센서": "로그인>지문로그인>지문센서",
            "spa>my>usage-limit-main": "MY>이용한도메인>이용한도메인",
            "app>LPMCDCB_V100.lc": "MY>즉시결제",
            "app>LPMCDCB_V210.lc": "MY>즉시결제>결제방법선택",
            "로그인>간편번호로그인": "로그인>간편번호로그인",
            "event>detail": "띵샵>이벤트>상세",
            "app>LPMCDCB_V230.lc": "MY>즉시결제",
            "메인>카드매니저>메인-카드매니저": "메인>카드매니저>메인-카드매니저",
            "spa>my>usage-billing": "MY>이용대금명세서>이용대금명세서",
            "front>satellite>main>discovery": "발견>메인",
            "메인>로카알리미>알림함": "로카알리미>알림함",
            "front>benefit>app-tech>main": "혜택>앱태크>메인",
            "로카페이>메인": "로카페이>메인",
            "front>benefit>coupang-thing>main": "혜택>쿠팡띵>메인",
            "event>type": "띵샵>이벤트>타입",
            "front>satellite>city-badge>home>main": "시티배지>홈>메인",
            "spa>mydata>personal-data-account>cash-roll": "마이데이터>마이캐시굴리기",
            "spa>benefit>half-landing": "혜택>반띵랜딩",
            "app>LPMAIAA_V100.lc": "Main-MW>로그인전",
            "spa>mydata>personal-data-account>rewards>attendance": "모빌리티>메인_마이데이터>리워드_출석체크>메인",
            "spa>benefit>halfThing": "혜택>반띵메인",
            "search": "띵샵>검색",
            "app>stamp>MPSTPAA_V100.lc": "모빌리티>스탬프>진행중",
            "spa>my>installment-payment-apply": "MY>분할납부(할부전환)>분할납부신청",
            "spa>mydata>personal-data-account>rewards>my-cash": "모빌리티>메인_마이데이터>리워드_마이캐시>메인",
            "로카페이>결제>QR스캔>카메라구동": "로카페이>결제>QR스캔>카메라구동",
            "공통>인증>개별인증>생체인증>Face ID인증": "공통>인증>개별인증>생체인증>FaceID인증",
            "front>satellite>city-badge>home>detail": "시티배지>홈>상세",
            "landing>kakaoLanding01.jsp": "기타>카드사용알림랜딩>이용내역(매출전표)",
            "spa>my>possession-card-inquiry": "MY>보유카드조회>이용가능카드",
            "spa>finance>revolving>revolving-info": "금융>일부결제금액이월약정(리볼빙)>일부결제금액이월약정(리볼빙)>이용중",
            "app>v1>LPBNFGA_V100.lc": "혜택>혜택리포트",
            "display>allmenu": "띵샵>전시>전체메뉴",
            "spa>mydata>personal-data-account>half-thing>card-bill": "반띵>결제금액>딴카드결제금액반띵",
            "로카페이>결제>현장결제>바코드_인증후": "로카페이>결제>현장결제>바코드_인증후",
            "front>finance>loans>long-term": "금융>장기카드대출",
            "mypage": "띵샵>마이페이지>상담",
            "혜택>이벤트>전체이벤트": "혜택>이벤트>전체이벤트",
            "spa>finance>receiptShortTernLoan": "금융>단기카드대출>단기카드대출신청",
            "spa>mydata>service-join>direct-payment-prv": "마이데이터>자산추가>상세정보전송요구동의_즉시결제완료후",
            "display>plan-shop>detail": "띵샵>전시>기획전>상세",
            "spa>my>my-info-inq": "MY>내정보관리>나의정보조회(정회원)",
            "native>main>MA_1_2": "메인>준회원",
            "spa>finance>shortTernLoanInfo": "금융>단기카드대출>단기카드대출안내",
            "order>sheet": "띵샵>주문",
            "display>shop": "띵샵>전시>샵",
            "spa>mydata>service-join>assets-linkage>bureau-choice": "마이데이터>자산연결>연결금융기관 선택",
            "spa>finance>revolving>revolving-bf-use": "금융>일부결제금액이월약정(리볼빙)>일부결제금액이월약정>이용안내",
            "spa>finance>receiptShortTernLoan>finish": "금융>단기카드대출>단기카드대출신청완료",
            "로그인>지문로그인>지문설정": "로그인>지문로그인>지문설정",
            "spa>finance>receiptShortTernLoan>receiptInfo": "금융>단기카드대출>단기카드대출정보확인",
            "spa>benefit>point": "혜택>포인트/마일리지조회",
            "spa>my>installment-payment": "MY>분할납부(할부전환)>분할납부메인",
            "mypage>thing-coin": "띵샵>마이페이지>띵코인",
            "spa>benefit>plus": "혜택>플러스",
            "spa>mydata>service-join>assets-linkage": "마이데이터>자산연결>서비스약관동의",
            "basket": "띵샵>장바구니",
            "spa>mydata>personal-data-account>cash-drive": "마이데이터>캐시드라이브",
            "로그인>지문로그인": "로그인>지문로그인",
            "spa>finance>shortTernLoanReceiptList": "금융>단기카드대출>내역조회",
            "spa>thing>onboarding-interest": "띵>관심사수집>관심사수집",
            "mypage>order>list": "띵샵>마이페이지>리뷰",
            "spa>mydata>main": "마이데이터>메인_자산관리",
            "app>LPARSBA_V100.lc": "메인>대표메인",
            "front>card>basic>credit>info>sub-main": "카드안내>신용카드>안내>서브메인",
            "로그인>자동로그아웃": "로그인>자동로그아웃",
            "app>main>MPMAIBG_V100.lc": "모빌리티>모빌리티리포트_교통비반띵참여불가",
            "혜택>혜택통합": "혜택>혜택통합",
            "로카페이>등록>ARS인증": "로카페이>등록>ARS인증",
            "front>benefit>forest-tour>my": "혜택>로카숲투어>MY",
            "spa>mobility>main": "모빌리티>메인",
            "landing>kakaoLanding02.jsp": "기타>카드사용알림랜딩>결제예정금액",
            "spa>local>lnc-v-dpay-dtl": "로컬>점심값반띵>내주변",
            "회원가입": "회원가입",
            "spa>my>business-special-limit-gate": "MY>입종별특별한도>입종별특별한도",
            "spa>mydata>service-join>assets-linkage>assets-list-transfer-request-agree": "마이데이터>자산연결>가입상품전송요구동의",
            "spa>my>noti-setting": "MY>알림설정>알림설정",
            "spa>my>onboarding": "MAIN>MY>앱온보딩",
            "회원가입>본인인증": "회원가입>본인인증",
            "로카페이>메인>Pay간편등록>Pay간편등록완료": "로카페이>메인>Pay간편등록>Pay간편등록완료",
            "spa>mydata>personal-data-account>myaccount": "모빌리티>메인_마이데이터>계좌_내계좌>메인",
            "MAIN>스플래쉬>LPAY": "MAIN>스플래쉬>LPAY",
            "spa>mydata>personal-data-account>rewards>reward": "모빌리티>메인_마이데이터>리워드_미션리워드>메인",
            "spa>mydata>service-join>setting>assets-linkage-manage": "마이데이터>자산설정>자산연결관리",
            "spa>card>booth": "카드>카드안내/신청-부스>카드상세 - 부스",
            "payment": "띵샵>결제",
            "spa>my>card-resign": "MY>카드해지신청>카드해지신청게이트페이지",
            "spa>my>payment-date-change": "MY>결제일변경>결제일변경",
            "spa>mydata>service-join>direct-payment-mydata-join": "마이데이터>자산추가>이용약관동의",
            "front>satellite>voc": "VOC>메인",
            "spa>benefit>couponBoxCommon": "혜택>쿠폰함_롯데백화점",
            "MAIN>스플래쉬>NPAY": "MAIN>스플래쉬>NPAY",
            "app>LPARSAA_V100.lc": "본인확인>인증",
            "spa>mydata>service-join>assets-linkage>certification-method-choice": "마이데이터>자산연결>인증서선택",
            "spa>my>account-change": "MY>결제계좌 조회/변경>결제계좌 조회/변경",
            "spa>mydata>service-join>assets-linkage>certification-method-choice-reconnect": "마이데이터>자산연결>2차인증방법선택",
            "front>finance>loans>long-term>apply": "금융>장기카드대출>신청",
            "로카페이>결제>바코드결제>결제완료": "로카페이>결제>바코드결제>결제완료",
            "app>LPMCDCB_V500.lc": "MY>즉시결제>즉시결제처리내역조회",
            "app>LPBNFBD_V100.lc": "혜택>포인트사용_L.POINTCase",
            "spa>mydata>personal-data-account>myassets": "모빌리티>메인_마이데이터>내자산>메인",
            "front>benefit>app-tech>loquiz": "혜택>앱태크>로퀴즈",
            "로카페이>결제>현장결제>숫자코드": "로카페이>결제>현장결제>숫자코드",
            "전체메뉴>설정": "설정",
            "spa>my>traffic-hipass-usage-history": "MY>교통 · 하이패스 이용내역>교통 · 하이패스 이용내역",
            "spa>mydata>service-join>assets-linkage>detail-information-transfer-request-agree": "마이데이터>자산연결>상세정보전송요구동의",
            "spa>my>payment-itemization": "MY>이용금액입금내역>이용금액입금내역",
            "로카페이>등록>ARS인증>연결중안내": "로카페이>등록>ARS인증",
            "spa>mydata>service-join>assets-linkage>assets-list-choice": "마이데이터>자산연결>자산연결(자산목록있음)",
            "app>LPBNFCH_V000.lc": "앱태크>쿠팡띵줍박스",
            "spa>my>split-card-payment-apply": "MY>나누기카드(할부전환)>나누기분할납부신청",
            "app>LPTRNEA_V100.lc": "트렌드>머니PICK>오늘의경제뉴스>한눈에보는오늘의뉴스",
            "로그인>간편번호로그인>간편번호설정>간편번호입력": "로그인>간편번호로그인>간편번호설정>간편번호입력",
            "spa>mydata>personal-data-account>expenditure": "모빌리티>메인_마이데이터>지출_지출분석>메인",
            "app>LPBNFQD_V100.lc": "혜택>국가바우처",
            "goods>detail": "띵샵>상품>상품상세",
            "display>gnbShop": "띵샵>전시>gnbShop",
            "로카페이>설정": "로카페이>설정",
            "MAIN>스플래쉬>튜토리얼>알림위치기반서비스동의": "MAIN>스플래쉬>튜토리얼>알림위치기반서비스동의",
            "app>LPBNFBC_V100.lc": "혜택>포인트캐시백",
            "app>LPBNFTA_V100.lc": "혜택>플랜할인프로모션>롯데카드플랜할인_신청전",
            "로카페이>메인>미등록대상>카드인증_비밀번호2자리": "로카페이>메인>미등록대상>카드인증_비밀번호2자리",
            "front>satellite>thing>detail": "띵콘텐츠>상세",
            "spa>mydata>service-join>assets-linkage>assets-connection-end": "마이데이터>자산연결>자산연결완료",
            "front>benefit>calendar": "혜택>캘린더",
            "app>LPBNFCD_V100.lc": "혜택>TOUCH>TOUCH혜택찾기",
            "app>LPMCDFM_V100.lc": "MY>해외이용종합안내",
            "spa>my>recieve-statment-change": "MY>명세서 수령방법 변경>명세서 수령방법 변경",
            "login": "회원>로그인>로그인페이지",
            "로그인>인증서로그인>공동인증서선택": "로그인>인증서로그인>공동인증서선택",
            "app>LPBNFBD_V600.lc": "혜택>포인트사용_L.POINTCase>납부할결제대금입력",
            "spa>my>virtual-account": "MY>가상계좌신청.조회>가상계좌신청.조회",
            "app>LPCSTRA_V100.lc": "고객센터>공지사항",
            "로카페이>등록>Face ID등록": "로카페이>등록>FaceID등록",
            "spa>my>noti-service>credit-care": "MY>알림서비스>가입 전",
            "spa>benefit>finance-half-thing": "혜택>금융이자반띵메인",
            "app>LPCVNDC_V100.lc": "생활편의>해외원화승인차단",
            "전체메뉴": "전체메뉴",
            "spa>mydata>personal-data-account>expenditure>card-bill": "마이데이터>지출_내지출>카드지출>카드청구서",
            "app>LPCSTEA_V100.lc": "고객센터>상담방법안내",
            "spa>my>usage-limit-home": "MY>이용한도>신용카드 이용한도 조회",
            "spa>card>card-apl>card-additional-services": "카드>신용카드>부가서비스신청",
            "app>LPBNFBD_V610.lc": "혜택>포인트사용_L.POINTCase>납부완료",
            "spa>card>card-issue>card-use-rg": "카드>카드 발급/수령>카드정보입력",
            "MAIN>스플래쉬>선택업데이트안내": "MAIN>스플래쉬>선택업데이트안내",
            "app>search>MPSEABA_V100.lc": "모빌리티>시외버스>검색",
            "spa>local>gde": "로컬>로카지도>지도",
            "spa>card>card-issue>issue-state-inq": "카드>카드 발급/수령>발급 진행상황",
            "spa>my>usage-limit-pick": "MY>이용한도pick>이용한도pick",
            "로그인>인증서로그인": "로그인>인증서로그인",
            "spa>my>card-password-cert": "MY>카드비밀번호등록,변경>카드비밀번호등록,변경본인인증",
            "app>search>MPSEABC_V100.lc": "모빌리티>시외버스>검색",
            "로그인>인증서로그인>금융인증서등록/취소": "로그인>인증서로그인>금융인증서등록/취소",
            "spa>my>split-card-payment": "MY>나누기카드(할부전환)>나누기카드메인",
            "혜택>포인트전환": "혜택>포인트전환",
            "로카페이>결제>현장결제>JUSTOUCH_결제요청": "로카페이>결제>현장결제>JUSTOUCH_결제요청",
            "app>LPBNFTE_V100.lc": "혜택>롯데계열사플랜할인>롯데계열사플랜할인_신청전",
            "mypage>my-coupon": "띵샵>마이페이지>내쿠폰",
            "mypage>favorite-goods": "띵샵>마이페이지>선물",
            "app>LPBNFTE_V400.lc": "혜택>롯데계열사플랜할인>플랜할인내역_신청후(1회차)",
            "app>LPOPBBB_V110.lc": "오픈뱅킹>계좌/카드한눈에보기(오픈뱅킹)>내계좌",
            "spa>card>cards>credit>application>member-validation-articles": "카드>신용카드>회원확인사항",
            "spa>card>card-apl>card-password": "카드>카드안내/신청>비밀번호설정",
            "app>LPMALAA_V300.lc": "기프트샷",
            "spa>mydata>service-join>app-signup-mydata-join": "마이데이터>자산연결>간편한 계좌 관리",
            "로카페이>결제>현장결제>QR코드": "로카페이>결제>현장결제>QR코드",
            "spa>my>document-application": "MY>서류발급신청>서류발급신청",
            "spa>card>gift-card": "카드>선불카드>상품권/기프트카드",
            "app>LPOPBBB_V100.lc": "오픈뱅킹>계좌&middot;카드",
            "app>LPBNFTE_V000.lc": "혜택>플랜할인",
            "spa>card>cards>credit>application>ocr-id-verification": "카드>카드안내/신청>OCR촬영",
            "app>LPBNFBA_V102.lc": "혜택>포인트/마일리지조회",
            "landing>kakaoLanding03.jsp": "기타>카드사용알림랜딩>이용금액입금내역",
            "app>LPMBRAB_V100.lc": "MEMBERS>MobileWeb로그인>로그인",
            "로그인>간편번호로그인>간편번호확인": "로그인>간편번호로그인>간편번호확인",
            "로그인>간편번호로그인>휴대폰인증": "로그인>간편번호로그인>휴대폰인증",
            "front>benefit>partners>lgu>apply": "혜택>파트너>LGU플러스>신청",
            "spa>card>card-apl>card-application-end": "카드>신용카드>신청완료",
            "front>finance>loans>long-term>repayment>apply": "금융>장기카드대출>상환>신청",
            "spa>my>usage-limit-down": "MY>이용한도하향>이용한도하향",
            "로카페이>결제>현장결제>QR코드_인증후": "로카페이>결제>현장결제>QR코드_인증후",
            "spa>my>card-password-change": "MY>카드 비밀번호 등록,변경>카드 비밀번호 등록,변경 정보입력",
            "app>LPCVNDB_V100.lc": "생활편의>해외이용안심설정",
            "spa>mydata>personal-data-account>myaccount>income-detail": "마이데이터>계좌_입금/출금>수입내역",
            "display>brand": "띵샵>전시>브랜드",
            "spa>my>usage-limit-gate": "MY>이용한도 게이트페이지>이용한도 게이트페이지",
            "spa>my>account-change-cert": "MY>결제계좌 조회/변경>결제계좌 조회/변경 공동인증",
            "app>LPPAYCA_V100.lc": "정기결제>안심쇼핑>안심쇼핑_미가입",
            "app>LPCUFAA_V100.lc": "생활편의>큐핏>큐핏",
            "회원>회원가입>결제서명등록": "회원>회원가입>결제서명등록",
            "front>benefit>app-tech>ads>watch": "혜택>앱태크>광고>시계",
            "마이데이터>계좌_내계좌>입출금>상세": "마이데이터>계좌_내계좌>계좌_전체거래내역",
            "spa>card>card-apl>card-stt-inf": "카드>신용카드>결제정보",
            "로카페이>설정>등록카드관리_결제수단": "로카페이>설정>등록카드관리_결제수단",
            "spa>my>noti-service>card-usage-noti": "MY>알림서비스>가입 전",
            "event>smallBizOwner>policyFunds": "셀리>소상공인진흥정책정책자금이벤트",
            "app>LPBNFDA_V300.lc": "혜택>이벤트>이벤트상세",
            "spa>my>document-application>utilization-itemization": "MY>서류발급신청>이용내역확인서",
            "spa>card>card-apl>card-use-notification": "카드>신용카드>카드사용내역 알림",
            "app>LPBNFTB_V100.lc": "혜택>롯데카드플랜할인>플랜할인내역_신청후(1회차)",
            "spa>card>card-issue>card-use-rg>cert": "카드>카드발급/수령>본인인증(비로그인시)",
            "front>corpmenu": "법인>법인메뉴",
            "spa>my>account-change-success": "MY>결제계좌조회/변경>결제계좌조회/변경완료",
            "spa>card>card-apl>card-ineligible": "카드>카드안내/신청>부적격",
            "spa>card>card-apl>card-billing-statement": "카드>신용카드>이용대금명세서 수신",
            "spa>card>card-apl>card-select-destination": "카드>신용카드>배송지선택",
            "spa>my>noti-service": "MY>알림서비스>알림서비스",
            "front>satellite>thing": "띵콘텐츠",
            "spa>my>noti-setting>psnl-credit": "MY>알림설정>개인/신용 정보수집 이용제공 동의 및 동의 철회",
            "app>LPCSTAL_V100.lc": "고객센터>결제승인이의제기신청",
            "app>LPCSTBA_V200.lc": "고객센터>이메일상담",
            "정기결제>안심쇼핑>안심쇼핑_이용중": "정기결제>안심쇼핑>안심쇼핑_이용중",
            "로카페이>설정>등록카드관리": "로카페이>설정>등록카드관리",
            "로카페이>등록>본인인증(휴대폰인증)": "로카페이>등록>본인인증(휴대폰인증)",
            "front>finance>loans>long-term>apply-completed": "금융>장기카드대출>신청완료",
            "로카페이>메인>앱카드미등록대상>앱카드등록안내(모든카드가BL)": "로카페이>메인>앱카드미등록대상>앱카드등록안내(모든카드가BL)",
            "display>category": "띵샵>전시>카테고리",
            "spa>card>card-apl>card-info": "카드>신용카드-부스>카드정보",
            "spa>card>card-apl>card-phone-cert": "카드>신용카드>본인확인",
            "spa>my>usage-limit-up": "MY>이용한도 상향>이용한도 상향",
            "spa>my>payment-date-change-success": "MY>결제일 변경>결제일 변경완료",
            "front>benefit>app-tech>loquiz>detail": "혜택>앱태크>로퀴즈>상세",
            "spa>finance>loan-transfer-index": "금융>대환대출>이용안내",
            "app>LPCSTHA_V200.lc": "고객센터>재발급신청>배송지선택_알림서비스_노출",
            "event>list": "띵샵>이벤트>목록",
            "front>card>issuance>status-info": "카드>카드발급상황",
            "spa>card>card-apl>card-income-type": "카드>신용카드>소득유형",
            "고객센터>분실신고>분실카드선택": "고객센터>분실신고>분실카드선택",
            "app>LPOPBBB_V200.lc": "오픈뱅킹>계좌/카드한눈에보기(오픈뱅킹)>내계좌>입출금내역",
            "app>LPCSTHA_V300.lc": "고객센터>재발급신청>재발급신청완료",
            "app>LPBNFCA_V120.lc": "MEMBERS>MobileWeb로그인>로그인",
            "app>LPCSTFA_V300.lc": "고객센터>분실신고>접수완료",
            "app>LPOPBBA_V101.lc": "오픈뱅킹>서비스가입>오픈뱅킹필수적동의",
            "spa>my>recieve-statment-change-success": "MY>명세서 수령방법 변경>명세서 수령방법 변경완료",
            "spa>finance>revolving>revolving-resign": "금융>일부결제금액이월약정(리볼빙)>일부결제금액이월약정 > 해지정보 확인",
            "app>mybus>MPMBSAA_V100.lc": "모빌리티>광역버스>검색>MY버스",
            "spa>my>business-special-limit-apply": "MY>업종별 특별한도>업종별 특별한도 신청",
            "front>my>payments>weekly>history": "정기결제>생활요금>위클리>이력",
            "app>LPBNFBB_V101.lc": "혜택>포인트전환>대상포인트/마일리지로전환",
            "spa>finance>revolving>revolving-apply-init": "금융>일부결제금액이월약정(리볼빙)>일부결제금액이월약정>약정결제비율설정",
            "searchResult": "띵샵>검색결과",
            "app>mybooking>MPBOOBA_V100.lc": "모빌리티>나의예약>고속.시외버스예매내역",
            "app>LPPAYCL_V100.lc": "정기결제>안심플러스>안심플러스_미가입",
            "mypage>mobile-coupon": "띵샵>마이페이지>모바일쿠폰",
            "spa>my>noti-service>credit-care-plus": "MY>알림서비스>가입 전",
            "mypage>review": "띵샵>마이페이지>리뷰",
            "app>main>MPMAICA_V100.lc": "모빌리티>디지로카KTX예매",
            "front>benefit>app-tech>ads>finance": "혜택>앱태크>광고>금융>보험",
            "spa>my>noti-setting>marketing": "MY>알림설정>마케팅정보 수신 동의 및 동의 철회",
            "app>LPARSAA_V200.lc": "본인확인>단품인증",
            "spa>my>installment-payment-history": "MY>분할납부(할부전환)>분할납부신청내역",
            "app>LPBNFOA_V100.lc": "혜택>친구에게카드추천",
            "spa>my>noti-service>large-payment-noti": "MY>알림서비스>가입 전",
            "app>LPBNFDA_V890.lc": "제휴이벤트>하나투어",
            "spa>card>cards>debit>catalog>card-list": "카드>카드안내/신청>체크카드",
            "app>LPOPBBA_V100.lc": "오픈뱅킹>서비스가입>오픈뱅킹계좌&middot;카드",
            "spa>local>home": "로컬>내주변",
            "로카페이>설정>카드본인확인서비스>신청전": "로카페이>설정>카드본인확인서비스>신청전",
            "app>LPPAYCM_V100.lc": "정기결제>폰케어>폰케어_미가입",
            "spa>card>card-apl>card-prv-all": "카드>신용카드>신분증인증 - 직접입력",
            "spa>mydata>service-join>setting>assets-linkage-manage-detail": "마이데이터>자산설정>자산연결상세",
            "spa>mydata>personal-data-account>expenditure>card": "마이데이터>지출_내지출>카드별",
            "spa>card>card-apl>card-id-ctf": "카드>신용카드>신분증인증안내",
            "spa>card>card-apl>card-id-ctf-drt": "카드>신용카드>신분증인증-직접입력",
            "spa>mydata>personal-data-account>loan": "모빌리티>메인_마이데이터>대출_내대출>메인",
            "app>LPPAYBF_V100.lc": "정기결제>도시가스>도시가스요금안내_미이용",
            "spa>card>card-apl>card-application-division": "카드>신용카드>신청구분",
            "spa>prepare": "혜택>반띵메인",
            "spa>card>card-apl>card-info-modify": "카드>신용카드>부가서비스신청",
            "salesReport>deposit": "셀리>매출/입금조회>입금내역>입금내역",
            "app>LPBNFDA_V100.lc": "혜택>이벤트>전체이벤트",
            "app>LPPAYCG_V100.lc": "정기결제>드라이빙케어>드라이빙케어_미가입",
            "MY>알림서비스>이용중": "MY>알림서비스>이용중",
            "spa>card-card-apl>with-application": "카드>신용카드>함께 신청",
            "app>LPCDXAA_V001.lc": "카드>브랜드카드>카드정보",
            "app>LPBNFCA_V300.lc": "혜택>TOUCH>외부제휴사일반형쿠폰상세",
            "app>LPBNFBB_V100.lc": "혜택>포인트전환",
            "spa>card-manager": "메인>카드매니저>카드추천",
            "app>ticketing>MPTRSBA_V100EB.lc": "모빌리티>고속버스>배차조회>편도",
            "mypage>order>detail": "띵샵>마이페이지>주문>목록",
            "app>seatselect>MPCHOAA_V100.lc": "모빌리티>시외버스>좌석선택>편도",
            "native>main>MA_1_1": "메인>정회원",
            "spa>my>usage-limit-up-complete": "MY>이용한도상향완료>이용한도상향완료",
            "order>complete": "띵샵>주문",
            "spa>cdd>customer-due-diligence-cert3": "CDD>인증3>고객확인의무재이행정보입력직업신분증",
            "spa>cdd>customer-due-diligence-cert2": "CDD>인증2>고객확인의무재이행 정보입력 직업 거래목적",
            "spa>card>cards>credit>catalog>card-detail": "카드>신용카드>카드정보",
            "app>LPCSTFA_V200.lc": "고객센터>분실신고>분실카드선택",
            "app>LPPAYBF_V500.lc": "정기결제>도시가스요금>도시가스요금안내_이용중",
            "app>LPBNFQD_V300.lc": "혜택>국가바우처>이용내역조회",
            "app>LPPAYCA_V300.lc": "MEMBERS>MobileWeb로그인>로그인",
            "app>LPCSTGA_V110.lc": "고객센터>분실신고해제>분실신고내역",
            "app>LPCSTHA_V110.lc": "고객센터>재발급신청>카드선택",
            "로카페이>결제>바코드결제>바코드_인증후": "로카페이>결제>현장결제>바코드_인증후",
            "front>lid>auth>sso>login" : "회원>로그인>로그인페이지",
            "spa>local>gde-search" : "로컬>로카지도>검색",
        };
      this.loaded = true;
    }
  
    async loadMappings() {
      // 이미 로드된 매핑 데이터를 그대로 반환
      console.log('Path mappings loaded from hardcoded data:', Object.keys(this.mappings).length);
      return this.mappings;
    }
  
    getKoreanTitle(englishPath) {
      return this.mappings[englishPath] || '';
    }
  }
  
  export default new PathMappingService();